### ISSUE TITLE
frontmatter 被输出成奇怪的格式

### ISSUE THREAD

**Issue by lingsamuel** [tidb-incubator/zh.md#10]
![image](https://user-images.githubusercontent.com/14567045/109377968-e1821f80-7909-11eb-931e-d10471462610.png)

1. 换行变成了 `&#xA;`
2. 方括号前多了个斜杠 `\["test"]`
3. 分隔符被移除了

貌似现在还不支持 frontmatter，能不能将其忽略？

**Comment by WPH95** [comment]
1. 手动使用 remark-frontmatter 这样的库对markdown 进行预先解析。
2. 等待这周末 preset-lint-zh ready，这个 preset-lint-zh 相对于 lint-zh 整合了 gfm fontmatter 等语法
