### ISSUE TITLE
顿号的规则错误

### ISSUE THREAD

**Issue by lingsamuel** [tidb-incubator/zh.md#11]
[文档](https://zh-style-guide.readthedocs.io/zh_CN/latest/%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7/%E5%B8%B8%E7%94%A8%E4%B8%AD%E6%96%87%E6%A0%87%E7%82%B9%E7%AC%A6%E5%8F%B7.html)中对顿号的说明：

> 顿号的形式为“、”，表示中文句子内部**两个及以上**并列成分之间的短暂停顿，这里的并列成分通常指同类的单字、词语或短句。

在检测规则中也强制要求一句话要有两个顿号（` warning  sentence pause'、' count:1, smaller than limit:2    ZH401
`）

但实际上顿号没有这样的要求。文档下的示例也显示了这一点：

> 任何教学大纲、教学方法或者评估方法的不同，都可能培养出创新的思维。

**Comment by yikeke** [comment]
同意检测规则有误，这是个充分不必要条件

**Comment by lingsamuel** [comment]
我的意思是这个文档该更新了 :flushed:

**Comment by yikeke** [comment]
哪句话需要更新？

**Comment by lingsamuel** [comment]
:joy: 我看错了，尴尬
