### ISSUE TITLE
定义 zh.md spec 和 spec 创建更新流程

### ISSUE THREAD

**Issue by WPH95** [tidb-incubator/zh.md#15]
为了规范化 zh.md，我们将定义 spec 和创建 spec 流程。

# spec 的定义
spec 将用于定义具体的中文规则，例如：引号的使用规范，逗号的使用限制等。
spec 中将包括该规则的：
- 状态 (实验性/测试/稳定/冻结)
- 详情
- 例子
- 实现

**Comment by lingsamuel** [comment]
人肉 diff 这些正误例子有点费劲，能否规范一些格式，便于自动化生成 diff？
