### ISSUE TITLE
TypeError: config.parser.tokenizeWhiteSpace is not a function

### ISSUE THREAD

**Issue by lingsamuel** [tidb-incubator/zh.md#7]
按照 readme 安装的

![image](https://user-images.githubusercontent.com/14567045/108975685-b7d6b780-76c1-11eb-89d7-c1738f82650b.png)

**Comment by gzponline** [comment]
![image](https://user-images.githubusercontent.com/12186221/109014976-9bea0a80-76ef-11eb-8af4-b1fff7cbea6e.png)

碰上同样的问题 这个项目怎么本地调试 有没有contibuting.md 这种的调试文档

**Comment by WPH95** [comment]
已经在研究中 应该是 package 生成的有问题

**Comment by WPH95** [comment]
@lingsamuel @gzponline PR #8 修复了这个问题，使用lint-zh版本大于等于 0.2.1 即可
感谢反馈
